name: print_color_example
description: Demonstrates how to use the print_color plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  print_color:
    path: ../

flutter:
  uses-material-design: true
