name: print_color
description: native dart print(), with the help of ansicolor
version: 2.1.2+7
homepage: https://github.com/MohamedSayed95/print_color

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ansicolor: ^1.0.2

flutter:
  plugin:
    androidPackage: net.msayed.print_color
    pluginClass: PrintColor