name: print_color
description: Print.color() to console, help with categorizing prints
version: 0.1.0
author:
- Creator <creative.mohamed.sayed@gmail.com>
homepage: https://github.com/MohamedSayed95/print_color

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ansicolor: ^1.0.2

flutter:
  plugin:
    platforms:
      android:
        package: net.msayed.print_color
        pluginClass: PrintColorPlugin
      ios:
        pluginClass: PrintColorPlugin