name: print_color
description: Print.color() help organizing debugging, very handy for the day debugging work
version: 1.0.1+5
homepage: https://github.com/MohamedSayed95/print_color

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ansicolor: ^1.0.2

flutter:
  plugin:
    androidPackage: net.msayed.print_color
    pluginClass: PrintColor